### ISSUE TITLE
移动文件之前没有创建目录

### ISSUE THREAD

**Issue by yy-Adrian** [y-Adrian/web#15]
[web](https://github.com/y-Adrian/web)/[docs](https://github.com/y-Adrian/web/tree/main/docs)/Vue环境配置.md 文件中应当先创建`/home/adrian/Documents/node`目录，直接移动会显示没有该目录，导致操作无法成功:
```shell
# 解压，整理、移动文件夹
tar xvf node-v18.15.0-linux-arm64.tar.xz 
mv node-v18.15.0-linux-arm64/* /home/adrian/Documents/node/
```

**Comment by y-Adrian** [comment]
This has been fixed in #16, so I close this issue.
